#! /bin/bash
### BEGIN INIT INFO
# Provides:          riemann-dash
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Starts Riemann
# chkconfig: - 80 15
# Description: Riemann event monitoring server.
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Pull in sysconfig settings
[ -f /etc/sysconfig/riemann-dash ] && . /etc/sysconfig/riemann-dash

RIEMANN_USER=rvm

DAEMON=/home/rvm/riemann-dash
NAME=riemann-dash
PID_FILE=${PIDFILE:-/var/run/${NAME}.pid}
LOCK_FILE=${LOCKFILE:-/var/lock/subsys/${NAME}}
NFILES=${NFILES:-32768}

start() {
    echo -n $"Starting ${NAME}: "
    ulimit -n $NFILES
    daemonize -u $RIEMANN_USER -c /home/rvm -p $PID_FILE -l $LOCK_FILE $DAEMON
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    return $RETVAL
}

stop() {
    echo -n $"Stopping ${NAME}: "
#    killproc -p ${PID_FILE} -d 10 $DAEMON
    killall -u rvm
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCK_FILE} ${PID_FILE}
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p ${PID_FILE} $DAEMON
        RETVAL=$?
        ;;
    restart|reload|fore-reload)
        stop
        start
        ;;
    *)
        N=/etc/init.d/${NAME}
        echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
        RETVAL=2
        ;;
esac

exit $RETVAL
