== Displaying Hystrix runtime information in a Browser

=== Hystrix Dashboard displays a Realtime Dashboard

https://github.com/Netflix/Hystrix/tree/master/hystrix-dashboard[Hystrix Dashboard^] is part of the Hystrix distribution. It displays runtime information about every Hystrix command and thread pool for the last minutes.

=== Installing and running Hystrix Dashboard

The installation has been scripted for you: you need to run `tools/hystrix-dashboard/maven-package-deploy.bat`.

The current installation will re-package the 1.3.16 version of Hystrix dashboard and add to it the latest (yet unreleased) changes to allow running it without an internet connection. Please have a look into `pom.xml` to see how you can adopt an already packaged WAR file to your environment.

Open your browser on http://localhost:8080/hystrix-dashboard/. Press btn:[Monitor Stream] with the default setting to display the aggregated stream from the Turbine dashboard.

Enter `http://localhost:8080/hystrixapp/hystrix.stream` to retrieve the information from the application directly.
